# Generated by Django 4.2.3 on 2023-07-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0005_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="total_rating",
            field=models.IntegerField(default=0),
        ),
    ]
